### ISSUE TITLE
About passing in elasticsearch_config argument for export_table_to_elasticsearch() method

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr-loading-pipelines#227]
To avoid the Elasticsearch node running in a docker container to publish the container's IP address (which will cause an error because it is not accessible from outside), It may be required to add an Elasticsearch config `{'es.nodes.wan.only': 'true'}`. Is it possible to add an optional argument `elasticsearch_config` to `export_table_to_elasticsearch()`?
https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/e2a7e08b356ce70af314507908c7df4a9f128d7b/hail_scripts/v02/utils/elasticsearch_client.py#L26

**Comment by bpblanken** [comment]
Closing because elasticsearch will be deprecated.
