### ISSUE TITLE
Adding Geno2MP allele frequencies

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr-loading-pipelines#235]
@anneodonnell commented on [Sat May 04 2019](https://github.com/broadinstitute/seqr/issues/842)

Geno2MP is the UW CMG data joint vcf with only variants <1% AF in the callset included from patients with disease and any family members they sequenced at the UW CMG. It would be great to include this as one of the allele frequencies in seqr though we shouldn't use it for filtering (as it's people with disease). But if we saw a variant in this database, it would be nice to know and be able to link to the variant page in Geno2MP (variant pages have some basic phenotype info and affected/unaffected status of the person with the variant). 

https://geno2mp.gs.washington.edu/Geno2MP/#/terms
There is a link to the bulk download on this page (about halfway down the page)

---

@hanars commented on [Mon May 06 2019](https://github.com/broadinstitute/seqr/issues/842#issuecomment-489672175)

At this point we are trying to put all new functionality into the new pipeline, which would mean waiting about a month for this. is that okay?

---

@anneodonnell commented on [Mon May 06 2019](https://github.com/broadinstitute/seqr/issues/842#issuecomment-489699425)

Yes, this can definitely wait. Thanks!

On May 6, 2019, at 11:53 AM, hanars <notifications@github.com<mailto:notifications@github.com>> wrote:

At this point we are trying to put all new functionality into the new pipeline, which would mean waiting about a month for this. is that okay?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_macarthur-2Dlab_seqr_issues_842-23issuecomment-2D489672175&d=DwMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=5vUteVBnqZNcgnM0ku5sYGt4mfHs2-emP5rDaWgEOes&s=xTTFhzmFecaW3UcOc-pawBWK1r9fl6_Q9WwCjWj6NuE&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACPM7UG6TGT6LA4WNMSJVFTPUBH7BANCNFSM4HKZXMFA&d=DwMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=5vUteVBnqZNcgnM0ku5sYGt4mfHs2-emP5rDaWgEOes&s=oNUeGNfHXNZf386C-GESaLbX8mCY2ZRwdzI8k8Jagog&e=>.

---

@bw2 commented on [Sun May 12 2019](https://github.com/broadinstitute/seqr/issues/842#issuecomment-491624875)

I remember looking into adding Geno2MP and I didn't find an allele frequency in the shared dataset.
The file has these fields:
```
##INFO=<ID=HPO_CT,Number=1,Type=Integer,Description="Observed Count of HPO Profiles">
##INFO=<ID=GENE,Number=1,Type=String,Description="Genes Overlapped with A Variant">
##INFO=<ID=MRNA,Number=1,Type=String,Description="mRNA Transcript Accession Number">
##INFO=<ID=FXN,Number=1,Type=String,Description="Function Annotation">
##INFO=<ID=HGVS_CDNA,Number=1,Type=String,Description="HGVS cDNA Variant Notation">
##INFO=<ID=HGVS_PROT,Number=1,Type=String,Description="HGVS Protein Variant Notation">
##INFO=<ID=ESP_AF,Number=1,Type=Float,Description="ESP Alternate Allele Frequency">
##INFO=<ID=EXAC_AF,Number=1,Type=Float,Description="ExAC Alternate Allele Frequency">
##INFO=<ID=G1K_AF,Number=1,Type=Float,Description="1000 Genome Alternate Allele Frequency">
##INFO=<ID=CADD,Number=1,Type=Float,Description="CADD Phred-Scaled Score">

1	69453	.	G	A	.	.	HPO_CT=1;GENE=OR4F5;MRNA=NM_001005484.1;FXN=synonymous;HGVS_CDNA=c.363G>A;HGVS_PROT=p.(K121=);ESP_AF=0;EXAC_AF=0;G1K_AF=0;CADD=0.008
1	69496	rs150690004	G	A	.	.	HPO_CT=9;GENE=OR4F5;MRNA=NM_001005484.1;FXN=missense;HGVS_CDNA=c.406G>A;HGVS_PROT=p.(G136S);ESP_AF=0.002364;EXAC_AF=0;G1K_AF=0;CADD=10.49
1	69540	.	G	A	.	.	HPO_CT=1;GENE=OR4F5;MRNA=NM_001005484.1;FXN=synonymous;HGVS_CDNA=c.450G>A;HGVS_PROT=p.(V150=);ESP_AF=0;EXAC_AF=0;G1K_AF=0;CADD=0.019
1	69552	rs55874132	G	C	.	.	HPO_CT=11;GENE=OR4F5;MRNA=NM_001005484.1;FXN=synonymous;HGVS_CDNA=c.462G>C;HGVS_PROT=p.(A154=);ESP_AF=0;EXAC_AF=0;G1K_AF=0;CADD=3.740
1	69559	.	G	A	.	.	HPO_CT=1;GENE=OR4F5;MRNA=NM_001005484.1;FXN=missense;HGVS_CDNA=c.469G>A;HGVS_PROT=p.(V157M);ESP_AF=0;EXAC_AF=4.9e-05;G1K_AF=0;CADD=23.4
```
It could be added the same way as ClinVar or HGMD. 
Also, @anneodonnell is this the kind of variant page you were thinking of?
https://geno2mp.gs.washington.edu/Geno2MP/#/variant/17/10534960/C%253EA/snp

---

@anneodonnell commented on [Sun May 12 2019](https://github.com/broadinstitute/seqr/issues/842#issuecomment-491627209)

It would be nice if they included the AC number but if not, then the HPO_CT number is useful. It’s the number of HPO phenotypes associated with the variant in the Geno2MP dataset. And it would be great if we could link directly to the variant page in Geno2MP to see what HPO terms these are.

We can also give Jessica Chong feedback on the extra fields we’d like to see in the shared file.

And yes, this is the type of variant page we’d like to link to (copied from below, same link): https://geno2mp.gs.washington.edu/Geno2MP/#/variant/17/10534960/C%253EA/snp<https://urldefense.proofpoint.com/v2/url?u=https-3A__geno2mp.gs.washington.edu_Geno2MP_-23_variant_17_10534960_C-25253EA_snp&d=DwMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=iBFcnLp8LbHQuOD0Pj1T7wUEOPE6m8_98kWmPmIgS6M&s=TgULfw6IiT1CVnQhGeXOx5vR4m7gckyouXuPEkywIa4&e=>

On May 12, 2019, at 4:03 PM, bw2 <notifications@github.com<mailto:notifications@github.com>> wrote:

I remember looking into adding Geno2MP and I didn't find an allele frequency in the shared dataset.
The file has these fields:

##INFO=<ID=HPO_CT,Number=1,Type=Integer,Description="Observed Count of HPO Profiles">
##INFO=<ID=GENE,Number=1,Type=String,Description="Genes Overlapped with A Variant">
##INFO=<ID=MRNA,Number=1,Type=String,Description="mRNA Transcript Accession Number">
##INFO=<ID=FXN,Number=1,Type=String,Description="Function Annotation">
##INFO=<ID=HGVS_CDNA,Number=1,Type=String,Description="HGVS cDNA Variant Notation">
##INFO=<ID=HGVS_PROT,Number=1,Type=String,Description="HGVS Protein Variant Notation">
##INFO=<ID=ESP_AF,Number=1,Type=Float,Description="ESP Alternate Allele Frequency">
##INFO=<ID=EXAC_AF,Number=1,Type=Float,Description="ExAC Alternate Allele Frequency">
##INFO=<ID=G1K_AF,Number=1,Type=Float,Description="1000 Genome Alternate Allele Frequency">
##INFO=<ID=CADD,Number=1,Type=Float,Description="CADD Phred-Scaled Score">

1       69453   .       G       A       .       .       HPO_CT=1;GENE=OR4F5;MRNA=NM_001005484.1;FXN=synonymous;HGVS_CDNA=c.363G>A;HGVS_PROT=p.(K121=);ESP_AF=0;EXAC_AF=0;G1K_AF=0;CADD=0.008
1       69496   rs150690004     G       A       .       .       HPO_CT=9;GENE=OR4F5;MRNA=NM_001005484.1;FXN=missense;HGVS_CDNA=c.406G>A;HGVS_PROT=p.(G136S);ESP_AF=0.002364;EXAC_AF=0;G1K_AF=0;CADD=10.49
1       69540   .       G       A       .       .       HPO_CT=1;GENE=OR4F5;MRNA=NM_001005484.1;FXN=synonymous;HGVS_CDNA=c.450G>A;HGVS_PROT=p.(V150=);ESP_AF=0;EXAC_AF=0;G1K_AF=0;CADD=0.019
1       69552   rs55874132      G       C       .       .       HPO_CT=11;GENE=OR4F5;MRNA=NM_001005484.1;FXN=synonymous;HGVS_CDNA=c.462G>C;HGVS_PROT=p.(A154=);ESP_AF=0;EXAC_AF=0;G1K_AF=0;CADD=3.740
1       69559   .       G       A       .       .       HPO_CT=1;GENE=OR4F5;MRNA=NM_001005484.1;FXN=missense;HGVS_CDNA=c.469G>A;HGVS_PROT=p.(V157M);ESP_AF=0;EXAC_AF=4.9e-05;G1K_AF=0;CADD=23.4

It could be added the same way as ClinVar or HGMD.
Also, @anneodonnell<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_anneodonnell&d=DwMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=iBFcnLp8LbHQuOD0Pj1T7wUEOPE6m8_98kWmPmIgS6M&s=juSfgB6cjjBK0IXO2buMmlqnIBWGIUuGeAcDF4gXZDo&e=> is this the kind of variant page you were thinking of?
https://geno2mp.gs.washington.edu/Geno2MP/#/variant/17/10534960/C%253EA/snp<https://urldefense.proofpoint.com/v2/url?u=https-3A__geno2mp.gs.washington.edu_Geno2MP_-23_variant_17_10534960_C-25253EA_snp&d=DwMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=iBFcnLp8LbHQuOD0Pj1T7wUEOPE6m8_98kWmPmIgS6M&s=TgULfw6IiT1CVnQhGeXOx5vR4m7gckyouXuPEkywIa4&e=>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_macarthur-2Dlab_seqr_issues_842-23issuecomment-2D491624875&d=DwMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=iBFcnLp8LbHQuOD0Pj1T7wUEOPE6m8_98kWmPmIgS6M&s=HXGoQZQ4tujWdRf2esE2o5wSAzChF_6VQn9CqW2kt1U&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACPM7UGSJXY2XILN236YWEDPVBZZPANCNFSM4HKZXMFA&d=DwMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=iBFcnLp8LbHQuOD0Pj1T7wUEOPE6m8_98kWmPmIgS6M&s=kMnNClPrzLKHHKg5b8apto1MwPantJ91EShTqjTnEGM&e=>.

---

@bw2 commented on [Sun May 12 2019](https://github.com/broadinstitute/seqr/issues/842#issuecomment-491630344)

If Geno2MP can add AC, AN and/or AF to the data file, it would be straight forward to integrate.
Also, it might be nice if they could list the actual HPO IDs (either broad or narrow) rather than the count.

---

@hanars commented on [Mon May 13 2019](https://github.com/broadinstitute/seqr/issues/842#issuecomment-491854666)

@mike-w-wilson have you started working on this yet? Did you bump into these issues?

---

@anneodonnell commented on [Mon May 13 2019](https://github.com/broadinstitute/seqr/issues/842#issuecomment-491930205)

I emailed Jessica Chong about this and copied Ben.

On May 13, 2019, at 10:50 AM, hanars <notifications@github.com<mailto:notifications@github.com>> wrote:

@mike-w-wilson<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mike-2Dw-2Dwilson&d=DwMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=Il0dfHNlshYRDuEPXUd-lX4IB0aTOZ6oa7pupI3cAzk&s=ES11uvgkdyl3hOLNrEkz0FC_ZJSvyhcsLrhxBYkMf4A&e=> have you started working on this yet? Did you bump into these issues?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_macarthur-2Dlab_seqr_issues_842-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DACPM7UHO7JP5P3QCXFQQHYLPVF5ZXA5CNFSM4HKZXMFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVIRWSQ-23issuecomment-2D491854666&d=DwMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=Il0dfHNlshYRDuEPXUd-lX4IB0aTOZ6oa7pupI3cAzk&s=TnK-YywQozWl3xINODodGEm7-1wV2A7H812pzeWq2tc&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACPM7UAY2O3V25A65DZT37DPVF5ZXANCNFSM4HKZXMFA&d=DwMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=Il0dfHNlshYRDuEPXUd-lX4IB0aTOZ6oa7pupI3cAzk&s=VNYe8ct9sfsB9u1SrK9_Cqzc1hHXZJ8KqV0ffqI6BlM&e=>.

---

@hanars commented on [Mon May 13 2019](https://github.com/broadinstitute/seqr/issues/842#issuecomment-491948046)

To reiterate, as @mike-w-wilson will be the one implementing this and not @bw2 please make sure he is the one included in these conversations

---

@bw2 commented on [Mon May 13 2019](https://github.com/broadinstitute/seqr/issues/842#issuecomment-491973827)

@hanars I've looked at this previously, and there are some questions to be answered before it's implemented. 

---

@hanars commented on [Mon May 13 2019](https://github.com/broadinstitute/seqr/issues/842#issuecomment-491978495)

Thats cool. Given that, you should really make sure to update the person who is currently actively working on it

**Comment by lynnpais** [comment]
We have a variant link to Geno2MP in seqr, so displaying AC is not a priority. Also Geno2MP is not likely to be updated under GREGoR.
