### ISSUE TITLE
Callset annotation across callsets

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr-loading-pipelines#237]
@anneodonnell commented on [Tue Jul 02 2019](https://github.com/broadinstitute/seqr/issues/936)

It would be great to have the AC from the internal exome callset also noted in seqr on the genome callset (and vice versa) so we recognize additional hits (or poor matches) across seqr data.

**Comment by mike-w-wilson** [comment]
Is this something that is still desired in the loading pipeline? If so, this request will likely need to change with the new hail backend loading pipeline

**Comment by anneodonnell** [comment]
Let's put this aside until the backend changes. The seqr link works to search for a variant across seqr at present, even if it isn't annotated that the variant is in the callset so we at least have that for our staff.

**Comment by hanars** [comment]
We may need to do something akin to this as part of the backend rewrite. In one of our planning meetings we should discuss how we want callset AF to work in the new backend as i is the only field that does not have an obvious way of porting it over. I think this is something we would want to discuss in a metting rather than explain in writing

**Comment by lynnpais** [comment]
Decided not to do for MVP.
