### ISSUE TITLE
Typical kubernetes Elasticsearch node types

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/seqr-loading-pipelines#253]
Hi, 

We are running into some issues with using AWS for running the pipeline and just want to compare with what is your typical number of Elasticsearch nodes and their sizes, especially CPU numbers of them. Could we get such an info (node type, number of them while creating an index)?

**Comment by hanars** [comment]
We use 3 data nodes, 3 client nodes, 3 master nodes, and 4 loading nodes. We use ECK's elasticsearch deployment for kubernetes, so it handles setting up the kubernetes pods for each node, but I think each node has one CPU? Client, master, and loading nodes use whatever the default memory ECK allocates, while data nodes have 44Gi of memory. Client and master nodes have 50Gi of disk space, loading nodes have 100Gi of disk space, and data nodes have 3200Gi of SSD disk space each. For very large projects, we spin up extra loading nodes (with the same specs as the "regular" loading nodes) just while we are doing the exporting step of the pipeline, and we will add enough nodes so we have one node per shard (i.e. if the final index will have 37 shards, we add 33 extra nodes to the 4 we already have running)

**Comment by bpblanken** [comment]
Closing because the question was answered and there's no work.
