### ISSUE TITLE
Fix validate MT error messages for WES and WGS 

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr-loading-pipelines#256]
In this function: https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/e2a7e08b356ce70af314507908c7df4a9f128d7b/luigi_pipeline/seqr_loading.py#L99 The text in the errors raised for when a VCF has or does not have coding and non_coding variants is wrong. The third check should say `...appears to be WES...` while the fourth should be `...appears to be WGS...`

**Comment by bpblanken** [comment]
All set on this one I think!  I have a patch that fixes up the relevant (at least what appeared to be relevant) tests too: 

[patchfile.patch](https://github.com/broadinstitute/seqr-loading-pipelines/files/10733453/patchfile.patch)
