### ISSUE TITLE
Add Siwei's noncoding constraint metric as an additional score

### ISSUE THREAD

**Issue by williamphu** [broadinstitute/seqr-loading-pipelines#293]
From Slack: https://atgu.slack.com/archives/CNNTF8Z46/p1639073008051400

Hello everyone! I want to share with the group a non-coding constraint metric we recently developed for assessing negative selection in the human genome, using our gnomAD v3.1.2 dataset. Briefly, selection was measured by the depletion of variation and a constraint Z score was assigned to each 1kb genomic window along the genome. Scores are provided in the .bed file below, alongside with a brief description of our method. Please feel free to use/test/explore it and we would appreciate any feedback or comments!!
https://www.dropbox.com/sh/rmhrd0w81xxnzzo/AADlczN-h1pqXiIcc8NVc_ula?dl=0

**Comment by mike-w-wilson** [comment]
Region based ref annotation: download_and_create_reference_datasets/v02/mito/write_mito_mitomap_ht.py

**Comment by mike-w-wilson** [comment]
Added in https://github.com/broadinstitute/seqr-loading-pipelines/pull/355

**Comment by hanars** [comment]
@mike-w-wilson is there a reason `gnomad_non_coding_constraint_z_score` is exported as an array? Would we ever expect multiple scores for a single variant?
