### ISSUE TITLE
Review VEP output and configuration

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr-loading-pipelines#307]
Anne said our genome data should have plenty of variants with a consequence of TF_binding_site_variant but my search showed we have none in the raw variant MT. Double check there isnt a ranking or filter issue in the pipeline and also if we need a flag to turn this consequence on.

**Comment by hanars** [comment]
Full list of "missing" consequences: 
```
feature_elongation
feature_truncation
initiator_codon_variant
regulatory_region_ablation
regulatory_region_amplification
regulatory_region_variant
TF_binding_site_variant
TFBS_ablation
TFBS_amplification
transcript_amplification
```

**Comment by bpblanken** [comment]
complete!
