### ISSUE TITLE
hail.utils.java.FatalError: ClassFormatError: Too many arguments in method signature in class file

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/seqr-loading-pipelines#348]
I wonder whether you ever faced the error or whether you can give any suggestions as to why it could be happening for us:

**hail.utils.java.FatalError: ClassFormatError: Too many arguments in method signature in class file**

when **mt.write** is run here:

https://github.com/broadinstitute/seqr-loading-pipelines/blob/master/luigi_pipeline/seqr_loading.py#L118

I asked it on Hail forum too:

https://discuss.hail.is/t/hail-utils-java-fatalerror-classformaterror-too-many-arguments-in-method-signature-in-class-file/2767

**Comment by hanars** [comment]
From the hail forum it looks like you were able to fix this with an updated version of spark and hail, so I will consider this issue resolved

**Comment by NLSVTN** [comment]
No, it works with old hail, spark but not with the new versions. The new ones actually give the same error.

**Comment by mike-w-wilson** [comment]
Hi -- we haven't hit this before and right now are running this pipeline on hail 0.2.97  on GCP dataproc so it seems like you may be onto something with EMR.

**Comment by NLSVTN** [comment]
Got it, thank you! Will keep looking into EMR.
