### ISSUE TITLE
Why upstream_gene_variant and downstream_gene_variant are omitted

### ISSUE THREAD

**Issue by SimonLi5601** [broadinstitute/seqr-loading-pipelines#352]
Hi team,
We noticed that in the current seqr loading pipeline, upstream_gene_variant and downstream_gene_variant are omitted from the VEP consequences terms, our stakeholder want to include those two consequences. Before we are going to do that, we would like to learn the rationale that why you want to omit in the first place. Is there unforeseen issue we might encounter if we include those two annotations. Thanks!

**Comment by mike-w-wilson** [comment]
Hi @SimonLi5601, we removed those consequence terms as they are really noisy and cause gene searches to return variants that we generally do not consider interesting. The decision to filter these consequences was made after conversations with our PIs. Also, seqr relies on the loading pipeline for filtering these terms and does not by default do any special handling of them so adding them back to the loading pipeline should not cause any unforeseen issues.

**Comment by SimonLi5601** [comment]
@mike-w-wilson  This is very helpful! Thank you!. I will close this issue.
