### ISSUE TITLE
Duplicate issue to #348

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/seqr-loading-pipelines#353]
Hi,

Just tried reopening the issue #348 but not sure how to do it, maybe have no permissions:

https://github.com/broadinstitute/seqr-loading-pipelines/issues/348

Could you check it out? The issue was resolved only for old hail and spark but our goal is to make it working with the new ones. Not sure why we get the specified error, wondering whether you ever faced it.

**Comment by bpblanken** [comment]
Closing because no further conversation.
