### ISSUE TITLE
Add ClinVar Version to index metadata 

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr-loading-pipelines#365]

**Comment by mike-w-wilson** [comment]
- [ ] Add clinvar version to clinvar ht globals in the write_cliver_ht [script](https://github.com/broadinstitute/seqr-loading-pipelines/blob/master/download_and_create_reference_datasets/v02/hail_scripts/write_clinvar_ht.py).

**Comment by bpblanken** [comment]
@mike-w-wilson Would you mind providing a little more context here?  I'm seeing the clinvar version (the date) already on present in the `ht` global fields:

```
(Pdb) hl.eval(ht.globals)
Struct(sourceFilePath='/tmp/clinvar.vcf.gz', genomeVersion='37', version='2023-02-08')
```

**Comment by mike-w-wilson** [comment]
Sorry @bpblanken, did not look into the download clinvar script to see it was already being put on the clinvar ht. Next step is to add that version annotation to the callset MT globals: https://github.com/broadinstitute/seqr-loading-pipelines/blob/3b21b5e6f11107842996566c5680ef485f6a1063/luigi_pipeline/seqr_loading.py#L102

**Comment by mike-w-wilson** [comment]
Hail has an i[ndex_globals()](https://hail.is/docs/0.2/hail.Table.html#hail.Table.index_globals) function that I think will be helpful here

**Comment by bpblanken** [comment]
Here's my shot at this!

[patchfile.patch](https://github.com/broadinstitute/seqr-loading-pipelines/files/10734382/patchfile.patch)

Wasn't super sure I needed `index_globals()` or how to fully test this... I'm sure I'm missing things regarding hail's lazy expressions!
