### ISSUE TITLE
Loading SV data locally

### ISSUE THREAD

**Issue by oferisak** [broadinstitute/seqr-loading-pipelines#372]
I have a local installation of seqr and have managed to upload SNV data produced by the DRAGEN germline application successfully. 
I could not, however, find documentation regarding the steps I need to take in order to upload SV data (specifically I have CNV calls produced using the aforementioned application). 

while there are comments in the sv_pipeline/genome/load_data.py file, with an example command, I am not sure what inputs are required and how to produce them.

Is there a document (similar to [this one](https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md)) specifying the steps required in order to upload SV data to a local instance of seqr?

thank you

**Comment by hanars** [comment]
Unfortunately there is not yet a standardized SV calling and annotation pipeline so seqr is unable to support SV calls for local installs. We hope to add this support in 2023
