### ISSUE TITLE
Noncoding exon transcript variants

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#378]
Issue: The majority of noncoding transcript exon variant are in obscure transcripts from coding genes (that are unlikely to be clinically or biologically interesting), a minority are actual transcripts of RNA genes that are never coding (the ones we are interested in).

Solution: We [the analysts] discussed adding 2 annotation categories for noncoding transcript exon variants to specifically select noncoding variants that are in the canonical transcript of that gene. This would replace the current “noncoding transcript exon variant” annotation (see screenshot) to the following 2 annotations:
“noncoding transcript exon variants (canonical)”
Hover over the question mark shows the following text: “a sequence variant that changes noncoding exon sequence in a canonical transcript for that gene, typically a noncoding gene”
“noncoding transcript exon variants (all)”
Hover over the question mark shows the following text: “a sequence variant that changes noncoding exon sequence in any transcript for that gene, often a noncoding version of a protein coding gene”

Corresponding seqr ticket is #[ 2804](https://github.com/broadinstitute/seqr/issues/2804)

**Comment by hanars** [comment]
@mike-w-wilson to implement this in seqr, we will need to update the pipeline so `transcriptConsequenceTerms` includes an annotation for `noncoding_transcript_exon_variant__canonical` that would be present if any of the `noncoding_transcript_exon_variant` transcripts were canonical for that gene. We would still need to keep the regular `noncoding_transcript_exon_variant` term in the list regardless

Per Anne;s comment on the lnked seqr ticket, this is "moderate-high priority to work on"

**Comment by hanars** [comment]
@bpblanken in the future can you link PRs to tickets? It makes looking things up later much easier

For future reference, corresponding PR is https://github.com/broadinstitute/seqr-loading-pipelines/pull/447
