### ISSUE TITLE
Tracking ClinVar submissions in seqr 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#385]
Related to seqr ticket https://github.com/broadinstitute/seqr/issues/3217

To better track variants curated and submitted by our team to ClinVar, we’d like to have variants annotated in seqr (similar to how we have the ClinVar status) if the submitter is [Broad Institute Rare Disease Group, Broad Institute](https://www.ncbi.nlm.nih.gov/clinvar/submitters/506627/). 

Here's one example of a variant submitted by our team - https://www.ncbi.nlm.nih.gov/clinvar/variation/1703227/?new_evidence=true

**Comment by hanars** [comment]
I would recommend we just pull the submitter (or list of submitters?) from the clinvar download and add that to the clinvar data, and then seqr can handle the logic of what to do with that info

**Comment by hanars** [comment]
If possible we would like to also pull the condition. LMK if you have any questions/ concerns

**Comment by hanars** [comment]
I also don't see submitter info in the VCF, but I though @bpblanken had looked into this already and figure out how to get it?
For condition information, I think its `CLNDN` or `CLNDISDB`

**Comment by bpblanken** [comment]
I don't think I've looked at this one enough to actually find the submitter.  I can take a peek at the file though.

**Comment by bpblanken** [comment]
I don't see submitter in the vcf either, seeing if it's somewhere else.

**Comment by bpblanken** [comment]
Looks like it's probably available in the [XML](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=clinvarset&id=RCV000000606), which is parseable but not fun 😬.

**Comment by hanars** [comment]
might be a question for @larrybabb
