### ISSUE TITLE
Add `ruff` with `pyflakes` and `pycodestyle` rules to repo.

### ISSUE THREAD

**Issue by bpblanken** [broadinstitute/seqr-loading-pipelines#417]
`pyflakes` rules will catch correctness issues like "unused import" and "unused var".
`pycodestyle` is the old `pep8` and will help with whitespace/formatting type issues (there's heavy overlap with black here).

**Comment by hanars** [comment]
Once we have done a first pass with these linting tools we may want to consider turning codacy on for this repo. We use it in the seqr repo and it lints PRs as a check on the PR so if users introduce new code that fails linting it will fail, and it makes enforcing linting easier going forward
