### ISSUE TITLE
Add prev call and genotype annotations to SV loading

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr-loading-pipelines#424]
From original seqr ticket https://github.com/broadinstitute/seqr/issues/3294 :

> In addition to SV data for samples on which we did not previously have SV calls, the v3 callset includes many samples included in v2, which was previously loaded to seqr. For the samples included in both v2 and v3, we anticipate ~10% of calls to be discordant. We'd like to be able to flag a subset of these discordant calls to make them easier for the analysts to review.

> Variants that were NOT called in the sample in v2 but are called in v3 - These would be tagged as New calls.
Variants that were called in the sample in both v2 and v3, but genotype differs (eg het vs hom) - These would be tagged as New genotype. It would be great if hovering over this tag could display the quality score and genotype from the previous callset.
For filtering behavior, we'd like filtering for "New" calls to return both of the categories listed above.

We will be adding `prev_call` and `new_call` fields to the genotypes to correspond with the gCNV fields, and adding a new `prev_num_alt` field derived from the concordance code. We will also add a `samples_new_call` field similar to what we have for gCNV

**Comment by larrybabb** [comment]
gated by Hail. next release of Hail should ungate this.
