### ISSUE TITLE
Make shuffle optional during split_multi_hts

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr-loading-pipelines#439]
Our AnVIL users occasionally submit VCFs with duplicate loci and multiallelics. When these files are loaded, they shuffling during the split_multi which is computationally expensive. Our internal callsets do not have this issue so we default to not allowing shuffle as is. Right now, we have duplicate versions of the luigi code(with the shuffle being the only difference)  in order to get AnVIL out-of-order key VCFs into seqr but we should have a single copy with an optional shuffle depending on the DAG type. William originally fixed this with a hardcoded shuffle https://github.com/broadinstitute/seqr-loading-pipelines/pull/286 but this is not desired since it will add unnecessary run time to our internal VCFs.

**Comment by mike-w-wilson** [comment]
This one, yes: https://console.cloud.google.com/dataproc/jobs/pyspark_compute_variants_AnVIL_WES_20230410_c2366d9e/monitoring?region=us-central1&project=seqr-project but not this is a contig issue https://console.cloud.google.com/dataproc/jobs/pyspark_compute_variants_AnVIL_WES_20230410_56f2a0b1/monitoring?region=us-central1&project=seqr-project I need to look into.

**Comment by bpblanken** [comment]
Closing in favor of #523
