### ISSUE TITLE
Set up precommit hook for repos

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr-loading-pipelines#441]

**Comment by mike-w-wilson** [comment]
gnomad_qc uses a similar [set up](https://github.com/broadinstitute/gnomad_qc/blob/main/.pre-commit-config.yaml) to what we are starting here

**Comment by bpblanken** [comment]
👍 

I'd started on this but left it in a bad state: https://github.com/broadinstitute/seqr-loading-pipelines/compare/benb/add_ci...benb/add_precommits?expand=1

**Comment by lynnpais** [comment]
Decided level of effort is not wort the minimal benefit.
