### ISSUE TITLE
Improve remap error messaging when a sample is not found + write unit tests.

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr-loading-pipelines#446]
Right now our script spits out the struct of `s and seqr_id` in the error message. morehttps://github.com/broadinstitute/seqr-loading-pipelines/blob/8e8e28519152256d4dc5c63e87a3463c2ad5e80a/luigi_pipeline/lib/hail_tasks.py#L178

It would be more helpful to change this language and parse the struct so the user knows exactly which ID, `s`,  is not being found in the dataset and also  which ID, `seqr_id`, to look for in the VCF since the majority of samples are repatiented to the `seqr_id`.

**Comment by bpblanken** [comment]
Repurposing to include writing some unit tests for the `remap_sample_ids` and `subset_samples` functions!
