### ISSUE TITLE
Add EXON and INTRON fields to sorted transcript consequences

### ISSUE THREAD

**Issue by nvnieuwk** [broadinstitute/seqr-loading-pipelines#448]
Hi, would it be a possibility to add the EXON and INTRON fields generated by VEP to the output of the loading pipeline? We'd like to add these fields in our institute's version of Seqr (It's a highly requested feature).

I think it should be as simple as adding `'exon'` and `'intron'` to this list: https://github.com/broadinstitute/seqr-loading-pipelines/blob/8e8e28519152256d4dc5c63e87a3463c2ad5e80a/hail_scripts/computed_fields/vep.py#L158. I'll gladly make a PR for this if you think this belongs here.

Is there an interest to add this to this repository or should we make our own fork of the loading pipeline and only add it there?

Thanks!

Greets
-Nicolas

**Comment by nvnieuwk** [comment]
I made a PR containing the suggestions #449

**Comment by hanars** [comment]
Hi Nicolas, thanks for proposing the change and thanks for submitting the PR! Changes to the seqr pipeline are not particularly useful without corresponding changes to the seqr UI to show the new data - how would you propose showing this information to users?

**Comment by nvnieuwk** [comment]
Hi, that makes absolute sense! We would want to add this information to each variant on the variant detail screen. I've not had a thorough look of where would be the best location (but maybe somewhere under or next to the allele counts?), would you have any suggestions where this would belong the best? 

Pinging @tomiles for a second opinion.

**Comment by hanars** [comment]
I think we are just confused what information this is adding, given that we already show a transcript's predicted consequence which will either be explicitly intronic or will be a consequence that is only possible when a variant is exonic.

**Comment by hanars** [comment]
Hi @nvnieuwk any update on how the display for this information would be different/ supplemental to what is already shown to users in seqr?

**Comment by tomiles** [comment]
@hanars This issue for adding VEP exon and intro info that @nvnieuwk raised came from our analysts. There currently is no convenient way to see in which intron or exon a variant is positioned. And this info is more intuitive to indicate where in a gene the variant is positioned without having to first follow the link out to the UCSC browser and check the gene track to find the exon/intron nr.

**Comment by nvnieuwk** [comment]
I'll give it a go! I'm very new to React so any feedback is welcome. I'll ping you when the PR has been opened

**Comment by nvnieuwk** [comment]
Hi @hanars I've been looking at where to add the exon and intron fields and I think it would be best to add these under the allele frequencies (2) or color ranges (1). Which one would you think is the best place for this or do you have a better proposal? 
 
![seqr_exon_intron_circles](https://github.com/broadinstitute/seqr-loading-pipelines/assets/101190534/4c8dfacd-6464-410b-a6ba-02d0849c0d8b)

Thanks!

**Comment by hanars** [comment]
Hi, I'm sorry I should have been more clear in my earlier discussion. Neither of these places is an appropriate place to show this data - it is transcript specific and therefore needs to be shown with transcript specific data. When you click on the predicted consequence, in this screenshot that would be the "intron variant" link, a popup appears with details of all the transcripts. You should be adding this information somewhere in there

**Comment by nvnieuwk** [comment]
> Hi, I'm sorry I should have been more clear in my earlier discussion. Neither of these places is an appropriate place to show this data - it is transcript specific and therefore needs to be shown with transcript specific data. When you click on the predicted consequence, in this screenshot that would be the "intron variant" link, a popup appears with details of all the transcripts. You should be adding this information somewhere in there

Oooh yes, I understand! Thank you :)

**Comment by nvnieuwk** [comment]
Hi @hanars I completely lost track of this and never got around to starting this. Is there any possibility that you guys could implement this?

**Comment by hanars** [comment]
I'm sorry, but we have very limited engineering bandwidth on our team and this is something that is unfortunately outside the scope for what we can handle at this time. We have planned work in the spring to reconfigure how we integrate VEP into seqr, so we could potentially add it at that time
