### ISSUE TITLE
Investigate issues related to SV v3 data loaded in seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#459]
**Describe the bug**
1. The 'New call' tag is appearing for all individuals even though it is not in the parents. Is this related to the seqr display or an issue with the data? E.g. [RGP_2007](https://seqr.broadinstitute.org/variant_search/variant/cohort_2911.chr2.final_cleanup_BND_chr2_1197/family/F031995_rgp_2007)
<img width="1221" alt="Screen Shot 2023-05-02 at 8 21 54 PM" src="https://user-images.githubusercontent.com/37872186/235812068-77c7ebea-c7bb-49fb-80cc-62c60c14fab3.png">

2. Additional calls missing from This Callset AC. 
E.g. https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0137383_1610000_f031954_rgp_
Callset AC=1 is shown, but is actually present in many cases [here](https://seqr.broadinstitute.org/variant_search/results/f49702786758e3a0a06ec8c765e63c78?page=1&sort=in_omim)
 
3. Quality scores missing in several cases. 
e.g. [RGP_1793](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0137411_1351937575_f031785_r) and [RGP_1780](https://seqr.broadinstitute.org/variant_search/results/8f85a60d0f833d4fa74228c0686a75ee?page=1&sort=revel)

**Comment by bpblanken** [comment]
Some thoughts from me:

3) From my understanding it seems as though the pipeline is behaving correctly here.  We implemented `New Call` as "Variants that were NOT called in the sample in v2 but are called in v3", and these are indeed variants/samples that have no concordance annotation and were not called in v2 (even though the genotype is 0/0).  We don't have the ability in the pipeline to label or not label a proband conditional on parent genotypes.  Maybe _seqr_ does?  I might be out of my depth on this one.    

4) This is a [bug](https://github.com/broadinstitute/seqr-loading-pipelines/issues/460)!  More details there.  

5)  These are all quality scores read correctly as `0` from the VCF I believe:

```
import hail as hl


mt = hl.import_vcf('phase3.fixChrX.sampleIDS.fixHeader.concordance.StrVCTVRE.vcf.gz', force_bgz=True, reference_genome='GRCh38')

mt1 = mt.filter_rows(mt.locus == hl.Locus('chr13', 51937575, 'GRCh38'))
mt1.filter_cols((mt1.s == 'RGP_1793_1') | (mt1.s == 'RGP_1793_2') | (mt1.s == 'RGP_1793_3'))
mt1.GQ.show()

+----------------+---------------+-----------------+-----------------+-----------------+
| locus          | alleles       | 'RGP_1793_1'.GQ | 'RGP_1793_2'.GQ | 'RGP_1793_3'.GQ |
+----------------+---------------+-----------------+-----------------+-----------------+
| locus<GRCh38>  | array<str>    |           int32 |           int32 |           int32 |
+----------------+---------------+-----------------+-----------------+-----------------+
| chr13:51937575 | ["N","<DEL>"] |              99 |              99 |               0 |
+----------------+---------------+-----------------+-----------------+-----------------+

mt2 = mt.filter_rows(mt.locus == hl.Locus('chr4', 16110293, 'GRCh38'))
mt2 = mt2.filter_cols((mt2.s == 'RGP_1780_1') | (mt2.s == 'RGP_1780_2') | (mt2.s == 'RGP_1780_3'))
mt2.GQ.show()

+---------------+---------------+-----------------+-----------------+-----------------+
| locus         | alleles       | 'RGP_1780_1'.GQ | 'RGP_1780_2'.GQ | 'RGP_1780_3'.GQ |
+---------------+---------------+-----------------+-----------------+-----------------+
| locus<GRCh38> | array<str>    |           int32 |           int32 |           int32 |
+---------------+---------------+-----------------+-----------------+-----------------+
| chr4:16110293 | ["N","<INS>"] |              99 |              99 |               0 |
+---------------+---------------+-----------------+-----------------+-----------------+


mt3 = mt.filter_rows(mt.locus == hl.Locus('chr1', 903351, 'GRCh38'))
mt3 = mt3.filter_cols((mt3.s == 'RGP_2007_1') | (mt3.s == 'RGP_2007_2') | (mt3.s == 'RGP_2007_3'))
mt3.GQ.show()

+---------------+---------------+-----------------+-----------------+-----------------+
| locus         | alleles       | 'RGP_2007_1'.GQ | 'RGP_2007_2'.GQ | 'RGP_2007_3'.GQ |
+---------------+---------------+-----------------+-----------------+-----------------+
| locus<GRCh38> | array<str>    |           int32 |           int32 |           int32 |
+---------------+---------------+-----------------+-----------------+-----------------+
| chr1:903351   | ["N","<DEL>"] |              32 |               0 |               0 |
+---------------+---------------+-----------------+-----------------+-----------------+

```

**Comment by hanars** [comment]
1) @lynnpais I think this is a semantic difference about what a "call" is, rather than a true bug. For gCNV data theres no such thing as a ref/ref call, it is just the absence of a call, so we never show "new call" for those. However, for SV data there is an actual call calling this as ref/ref, with associated quality scores etc. Therefore, this is technically a "New Call" - in the previous round there was no call for this sample in this variant, and now there is a ref/ref call. In my mind this is similar to how we show "New Genotype" on ref/ref calls as well -in a previous round this was het, now it is hom ref, so that is a new genotype. 

We can modify seqr's search and display behavior to match what you as a user would want, but technically speaking what is currently being shown is the most accurate

2) Okay, since there is a separate ticket to track fixing that bug we can call this investigation over!

3) I will follow up with Alba in slack. If needed we an make a new ticket based on her response, but we can call the investigation on this one done
