### ISSUE TITLE
Bad boolean logic

### ISSUE THREAD

**Issue by tkallady** [broadinstitute/seqr-loading-pipelines#475]
This line is causing a bug due to operator precedence. Should have bracket around == expression.

https://github.com/broadinstitute/seqr-loading-pipelines/blob/91ae7b482b5fa6067c71c2dc938f5bcedbb8be8b/hail_scripts/computed_fields/vep.py#LL62C1-L62C21

**Comment by bpblanken** [comment]
@tkallady thank you for the bug report!
