### ISSUE TITLE
Drop fields that seqr/loading pipeline does not use after import

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr-loading-pipelines#522]
The pipeline currently carries unused fields, e.g. FORMAT/PL, FORMAT/AF, up until fields are selected for export. We should drop the unused fields by only selecting the required fields after VCF import. Selecting used fields rather than dropping known unused fields would protect us from surprises in the AnVIL loading pipeline. The fields we want to keep are below:

Entry fields:
GT
AD
GQ

Row Fields:
locus (key)
alleles (key)
rsid
filters

This would resolve a recurring issue we have seen in AnVIL loading requests where PLs are not formatted properly. It also reduces the amount of work the pipeline has to do.

**Comment by bpblanken** [comment]
Already done as part of v3 pipeline work.
