### ISSUE TITLE
Investigate options for processing and annotating longread data

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#527]
The CZI/Shasta longread data did not load into seqr for several reasons including the format which we can work with the UCSC team on. On the seqr side, some updates will need to made to process larger variants. Need to investigate what events are being captured through longread sequencing, and how to process/ annotate them in seqr.

**Comment by bpblanken** [comment]
Do we have access to the `CZI/Shasta` vcf?

**Comment by lynnpais** [comment]
@bpblanken I've added you to the workspace with the one family I tried to load to seqr.

**Comment by hanars** [comment]
Any changes to support this data should only be added to the v3 pipeline

**Comment by bpblanken** [comment]
Workspace is here:https://app.terra.bio/#workspaces/rare-disease-czi/CZI_test

**Comment by bpblanken** [comment]
Looked at the VCF:

```
In [7]: mt.describe()
----------------------------------------
Global fields:
    None
----------------------------------------
Column fields:
    's': str
----------------------------------------
Row fields:
    'locus': locus<GRCh38>
    'alleles': array<str>
    'rsid': str
    'qual': float64
    'filters': set<str>
    'info': struct {
        END: int32,
        SVTYPE: str,
        CUTPASTE: bool,
        SVLEN: int32,
        READS: array<str>
    }
----------------------------------------
Entry fields:
    'GT': call
    'GQ': int32
    'DP': int32
    'MIN_DP': int32
    'AD': array<int32>
    'VAF': array<float64>
    'PL': array<int32>
    'MED_DP': int32
    'PS': int32
    'CN': int32
----------------------------------------
Column key: ['s']
Row key: ['locus', 'alleles']
```

we're completely fine to attempt a load here.  The only required fields for snv_indels are `locus`, `alleles`, `filters`, `rsid`, `GT`, `DP`, `AD` and those are all satisfied.

**Comment by bpblanken** [comment]
Some more info on the long indels:

- There's quite a few locii that are "multi-allelics".  The new pipeline (and the existing one, after [this](https://github.com/broadinstitute/seqr-loading-pipelines/pull/531)) have support for this.  I have a feeling that this was part of the issue.
- There's definitely long strings in there... see quite a few with length over 1500.
- Our current callsets do have long strings as well, they're just less long:

```
In [33]: mt = hl.read_matrix_table('gs://seqr-loading-temp/v03/GRCh38/SNV/remapped_and_subsetted_callsets/72851a88efaacba8ba16ca56d120fcd6aa45386a97b7bcbccc085ef241a45364.mt')

In [34]: alleles_list = mt.alleles.take(1000000)
[Stage 7:=============================>                             (1 + 1) / 2]
In [35]: [x for x in alleles_list if any(len(y) > 500 for y in x)]
Out[35]:
[['C',
  'CTATAGTGACTTAACGGAGGGCACTGTGTATGCTATAGTGACTTAACGGAGGGCACCGTGTGTGTTATAGTGACTTAACGGAGAGCACCGTATGGTGCTATAGTGACTTAACGGAGGGCACTGTGTGTGTTATAGTGACTTAACGGAGGGCACCGTGTGTGTTATAGTGACTTAACGGAGGGCACCGTATGGTGCTATAGTGACTTAACGGAGGGCACCGTATGGTGCTATAGTGACTTAACGGAGGGGACCGTGTGGTGCTATAGTGACTTAACGGAGGGCATTGTGTGTGCTATAGTGACTTAACGGAGGGCACCGTACGGTGCTATAGTGACTTAACGGAGGGCACTGTGTGTGCTAAAGTGACTTAACGGAGGGGACCGTGTGGTGTTATAGTGACTTAACGGAGGGCACCGGATGGTGCTATAGTGACTTAACGGAAGGGACCGTGTGGTGTTATAGTGACTTAACGGAGGGCACTGGATGGTGCTATAGTGACTTAACGGAGGGGACCGTGTGGTGTTATAGTGACTTAACGGAGGGCACCGTGTGGTGT'],
 ['C',
  'CACTAACACATACACATACACACACACTAACACATACACATACATATATACTAACATACACATACACACATACTAACACATACACATACACACATACTAACACATACACATACAGATATACTAACACAGACACATACACACTAACACATACACATACACACTAACATACACATACACACACTAACACATACACATACACACATACTAACACATACACACACACTAACACATACATATATACTAACACATACACATACACACATACTAACATACACAAACATACACATACACACATACTAACACATACACACACAAACACATACACATACACACATACTAACACATACACATACACATACTAACACATACACATACACACATACTAACACATACACATACATATATACTAACACACACACTAACACATACACACATACTAACACATACACACACTAACACATACACACACTAACACATACACATACACACATACTAACACATACACACACTAACACACACATACACACACTAACACACATACACACTAACACATACACATGCACACATACTAACACATACACATACATATAT']]
```

I wouldn't be surprised if there's an elasticsearch limit that got hit that we won't have to worry about in the future.  Hail appears to be totally fine here.

**Comment by bpblanken** [comment]
Yeah, longest string in the long read database is 94170 bases 🤣

**Comment by hanars** [comment]
I do worry that like the response size for search results might get prohibitively large/ slow if we have to stream lots of these big strings. And also, I don't think an analyst would ever *want* to look at a 94170 character string representation of an indel, I think they would want to represent it as a small SV. So we should think about if we want to do special handling in our pipeline around these, or if we want to do an MVP where we just show these like regular indels with massive strings and worry about how to show those in a later iteration

**Comment by bpblanken** [comment]
According to [wikipedia](https://en.wikipedia.org/wiki/Indel), Indels ≥ 50 bases in length are classified as [structural variants](https://en.wikipedia.org/wiki/Structural_variation) fwiw.
