### ISSUE TITLE
Update constraint metrics for mt variants

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#561]
Existing Helix constraint info is old. Remove Helix constraint info which currently shows as a red tag.

Update with Nicole Lake's new data from supplemental tables in the study (https://www.biorxiv.org/content/10.1101/2022.12.16.520778v2)

Display the mitochondrial local constraint score (MLC) in a traffic light system like we do for the in silico tools
High constraint is >=0.75 - red; 0.50-0.74 is yellow; <0.50 is green

**Comment by bpblanken** [comment]
`local_constraint_mito` is now present on the MITO annotations table:

```
In [4]: hl.read_table('gs://seqr-hail-search-data/v03/GRCh38/MITO/annotations.ht').local_constraint_mito
Out[4]: <StructExpression of type struct{score: float32}>
```

**Comment by bpblanken** [comment]
@lynnpais We'll need a UI ticket to implement the traffic light in the UI.
