### ISSUE TITLE
Document how ONT longread data differs from short read

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#577]
Create a dif file in Google docs showing how ONT longread data differs from short read such as quality scores, etc.

Anne & Lynn will then review this file

**Comment by bpblanken** [comment]
@lynnpais here's the [google doc](https://docs.google.com/spreadsheets/d/1qi06JVZ7SPEnfhPIqJ9KKTEJ-P_b2ssQn7KlAmGk6yI/edit?usp=sharing)
