### ISSUE TITLE
Update in silico scores based on new guidelines

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#616]
Related to the work in seqr ticket #3505. 

We would like to have annotations matching up with new guidelines from ClinGen. They put forth evidence ranges of scores falling into certain categories. To be consistent, we need to be using the scores for FATHMM, SIFT, PolyPhen
Currently, the old categories are being displayed.

Colors will be based on ranges as shown here but will submit another app ticket to update this in seqr <img width="965" alt="255224354-089a5837-7cf6-490a-8f9e-8a608dda497d" src="https://github.com/broadinstitute/seqr/assets/37872186/fc618057-2465-419f-93a5-1906299d7db5">

**Comment by bpblanken** [comment]
Prefer score vs pred.

**Comment by lynnpais** [comment]
Update for V3 only

**Comment by bpblanken** [comment]
This is complete.
