### ISSUE TITLE
Updating the VEP version in container image.

### ISSUE THREAD

**Issue by barslmn** [broadinstitute/seqr-loading-pipelines#626]
I felt this might require its own issue. But related to #624.

There have been some breaking changes from VEP release 99 like gnomad column name changes IIRC.

How are these column names are handled in the seqr backend and frontend?
Would updating to VEP release 110 break anything downstream?

**Comment by bpblanken** [comment]
@barslmn we have an issue related to this already (https://github.com/broadinstitute/seqr-loading-pipelines/issues/307) that has been prioritized on our roadmap (just, unfortunately, below a few other things).  Regarding the column names, we generally extract from VEP into our own Hail annotations, which have then been exported to elasticsearch and read by the seqr backend.  

I'm going to go ahead and close this one, but feel free to comment on #307!

**Comment by barslmn** [comment]
Thanks i will continue there.
