### ISSUE TITLE
Why the htslib is installed?

### ISSUE THREAD

**Issue by barslmn** [broadinstitute/seqr-loading-pipelines#629]
https://github.com/broadinstitute/seqr-loading-pipelines/blob/aed106c8250b527197b39ddc6374d85b2942b673/docker/Dockerfile#L59C1-L59C1

Is htslib used?

**Comment by bpblanken** [comment]
`htslib` and `samtools` are required by VEP to run.  Now that VEP produces their own pre-built docker image, we are using that and no longer need a manual `htslib` install.

**Comment by bpblanken** [comment]
The new pipeline runner docker image will resolve this: https://github.com/broadinstitute/seqr-loading-pipelines/issues/820
