### ISSUE TITLE
Write a set of utilities to determine if reference data is out of date.

### ISSUE THREAD

**Issue by bpblanken** [broadinstitute/seqr-loading-pipelines#658]
- Compare the globals (paths/versions/enums/selects) of a live hail table with that computed from the in-code config.py. 
Potentially run into some nuance with clinvar (clinvar version is a date andis computed dynamically by downloading the file from ftp), and the other files where version is embedded in the hail table and isn't statically defined in the config.
- This should return the out of sync reference datasets if they exist, else “None” or an empty list.
- This will also slot into the “def complete” function of the UpdatedReferenceDatasetCollectionTask (we’re successfully updated if there’s nothing to update).

**Comment by jklugherz** [comment]
Do we still want to write a table to the `destination_path` If there is nothing to update? if not, this requires a slight refactor to  `BaseUpdateTask.run()` as well. We could add a new function like `def should_write(self) -> bool: return True` where the default behavior is to write the table unless overridden by the child class
