### ISSUE TITLE
Refactor dataset CONFIG dict into models

### ISSUE THREAD

**Issue by jklugherz** [broadinstitute/seqr-loading-pipelines#772]
Throughout the v03 pipeline code we rely heavily on the CONFIG dictionary defined in [v03_pipeline/lib/reference_data/config.py](https://github.com/broadinstitute/seqr-loading-pipelines/blob/main/v03_pipeline/lib/reference_data/config.py#L177), which holds external dataset configurations.

Refactor this dict into something more object oriented (like enums or python dataclasses) and replace all the references to the dict, (including the many mock config dicts in tests, like [this](https://github.com/broadinstitute/seqr-loading-pipelines/blob/main/v03_pipeline/lib/tasks/reference_data/update_variant_annotations_table_with_updated_reference_dataset_test.py#L226)), to make the code cleaner and more maintainable. (One issue with the dict is that we have no way to enforce requirements like if one key is present, another must also be.)

This is also a good time to add `ReferenceGenome` as an attribute of the dataset (suggested in a code review [here](https://github.com/broadinstitute/seqr-loading-pipelines/pull/679#discussion_r1472297938)).

**Comment by lynnpais** [comment]
Review when we are doing the database migration.
