### ISSUE TITLE
Use the `ETag` of the clinvar submission and vcf to cache our gcs temp files.

### ISSUE THREAD

**Issue by bpblanken** [broadinstitute/seqr-loading-pipelines#823]
```
bblanken@wmbbe-67c seqr-loading-pipelines % curl -I HEAD https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/submission_summary.txt.gz | grep ETag
ETag: "f9c1461-61ba3f958bf2e"
```

or something else!

**Comment by bpblanken** [comment]
Merged, but would love to see it working!

**Comment by jklugherz** [comment]
yesterday's [run](https://console.cloud.google.com/dataproc/jobs/UpdateVariantAnnotationsTableWithNewSamplesTask_F4ZRS/monitoring?region=us-central1&project=seqr-project) used the cached clinvar table 😎
